#!/usr/bin/env python3
""" perform a development install of jupyterlab_git
    On Binder, this will run _after_ the environment has been fully created from
    the environment.yml in this directory.
    This script should also run locally on Linux/MacOS/Windows:
        python3 binder/postBuild
"""
import subprocess
import sys
from pathlib import Path


ROOT = Path.cwd()

def _(*args, **kwargs):
    """ Run a command, echoing the args
        fails hard if something goes wrong
    """
    print("\n\t", " ".join(args), "\n")
    return_code = subprocess.call(args, **kwargs)
    if return_code != 0:
        print("\nERROR", return_code, " ".join(args))
        sys.exit(return_code)

# install github extension
#_("jupyter", "labextension", "install", "@jupyterlab/github")

# install TOC extension
_("jupyter", "labextension", "install", "@jupyterlab/toc")

# install topbar extension
#_("jupyter", "labextension", "install", 
#    "jupyterlab-topbar-extension", 
#    "jupyterlab-system-monitor", 
#    "jupyterlab-topbar-text", 
#    "jupyterlab-theme-toggle",
#)
_("jupyter", "labextension", "install", 
    "jupyterlab-topbar-extension", 
    "jupyterlab-theme-toggle",
)

# list the extensions
_("jupyter", "server", "extension", "list")

# initially list installed extensions to determine if there are any surprises
_("jupyter", "labextension", "list")


